name: "tmp-branch-action"
description: "GitHub action that creates a branch (remotely, on a Github repository), then deletes it in a \"post\" step."
inputs:
  branch:
    description: "Branch name to create"
    required: true
  repository:
    description: "Repository to create the branch on, defaults to $GITHUB_REPOSITORY"
  sha:
    description: "SHA to create the branch at, defaults to $GITHUB_SHA"
  keep:
    description: "Set to a truthy value to keep the branch after the \"post\" step"
runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
